on:
  push:
    branches:
      - main

name: Shiny App Deployment

env:
  APP_NAME: shiny_app_dev

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e "install.packages(c('DT', 'shiny', 'shinyjs', 'tidyverse', 'shinycssloaders', 'Kendall', 'viridis', 'ggpubr', 'reshape2', 'quantreg', 'invgamma', 'rsconnect', 'remotes'), type = 'binary')" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Set Credentials
        run: Rscript -e "rsconnect::setAccountInfo(name='mpviz', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
      - name: Deploy to shinyapp.io
        run: Rscript -e "rsconnect::deployApp(appName=${{env.APP_NAME}})"