on:
  push:
    branches:
      - main

name: Shiny App Deployment

env:
  APP_NAME: shiny_app_dev

jobs:
  deploy-shiny:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.4'
      - name: Install dependencies
        run: |
          install.packages(c('DT', 'shiny', 'shinyjs', 'tidyverse', 'shinycssloaders', 'Kendall', 'viridis', 'ggpubr', 'reshape2', 'quantreg', 'invgamma', 'rsconnect', 'remotes'))
        shell: Rscript {0} 
      - name: Set Credentials
        run: |
          rsconnect::setAccountInfo(name='mpviz', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})
        shell: Rscript {0}
      - name: Deploy to shinyapp.io
        run: |
          rsconnect::deployApp(appName=${{env.APP_NAME}})
        shell: Rscript {0}
