on:
  push:
    branches:
      - main

name: Shiny App Deployment

env:
  APP_NAME: shiny_app_dev

jobs:
  deploy-shiny:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.0.4
      - name: Install dependencies and cache
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect
      - name: Set Credentials
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='mpviz', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
      - name: Deploy to shinyapp.io
        run: |
          setwd('./R')
          rsconnect::deployApp(appName="shiny_app_dev")
        shell: Rscript {0}
